user_settings:
  userId: 08d7952ab8ae993f
  userName: p1ckl
  email: egeerksen@gmail.com
  timeShift: 3.0
  planners: []
---
app_settings:
  base_url: https://time2meetapis.yyjlincoln.app/
  init: true
