user_settings:
  init: false
  password: null
  timezone: 10
  username: null
---
r_settings:
  delete: null
  patch: null
  planner:
    get:
      plannerId: 471ff606a01b89bd12
    post:
      notAfter: 1639297581.309199
      notBefore: 1638692781.309199
      plannerName: Meeting
---
app_settings:
  base_url: https://time2meetapis.yyjlincoln.app/
